#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Guennadi Liakhovetki, DENX Software Engineering, <lg@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#
# test.o for compile success.
obj-y	:= test.o 
 
extra-y	:= led.o memory.o uart.o 
#extra-y	+= uart.o 
#extra-y	+= memory.o 
